spring:
  profile: development
  application:
    name: "@project.artifactId@"
    version: "@project.version@ (@env.GIT_COMMIT@)"

error-manager:
  enabled: true

error-handling:
  enableExceptionLogging: true
  enableStacktraceLogging: true
  enableExceptionEvent: false
  enableExceptionDecoding: true
  enableUnknowExceptionMapping: true

logging:
  level:
    root: INFO
    com.intesasanpaolo.bear: INFO
    com.intesasanpaolo.bear.config: DEBUG
    com.intesasanpaolo.bear.connector.jdbc: DEBUG
    org.keycloak: DEBUG

controllers:
  tracing:
    enabled: true

session-manager:
  mocked: ${MOCK_SESSION:true}
  allow-guest-session: ${MOCK_SESSION:true}
  allow-empty-session-id: ${MOCK_SESSION:true}
  endpoint: ${SESSION_MANAGER_URL:http://localhost:8080}/internalsession

management:
  health:
    probes:
      enabled: true

drools:
  application:
    name: "@project.name@"
    version: "@project.version@ (@env.GIT_COMMIT@)"
    groupId: "com.intesasanpaolo.bear.tits0.engine"

connectors:
  restConfigurations:
    default:
      timeout: 500000
      mocked: ${MOCKED:true}
      enabledTracing: true
      randomMock: false
    items:
      GetControlloConnector:
        url: ${CORE_ENGINE_URL:http://core-tit-engine-v1-tits0-svil.cloudfinanza-svil.intesasanpaolo.com}/controlli/{controlloId}
        path: classpath:mocks/controlli/
        files:
          - getControlloOK.json
      GetInstanceConnector:
        url: ${CORE_ENGINE_URL:http://core-tit-engine-v1-tits0-svil.cloudfinanza-svil.intesasanpaolo.com}/controlli/{controlloId}/instances/{instanceId}
        path: classpath:mocks/controlli/
        files:
          - getInstanceOK.json
      ListSchedulazioneControlloConnector:
        url: ${CORE_ENGINE_URL:http://core-tit-engine-v1-tits0-svil.cloudfinanza-svil.intesasanpaolo.com}/controlli
        path: classpath:mocks/controlli/
        files:
          - listSchedulazioneControlloOK.json
      ListInputConnector:
        url: ${CORE_ENGINE_URL:http://core-tit-engine-v1-tits0-svil.cloudfinanza-svil.intesasanpaolo.com}/controlli/{controlloId}/input
        path: classpath:mocks/controlli/
        files:
          - listInputOK.json
      ListInstanceBySearchParamsConnector:
        url: ${CORE_ENGINE_URL:http://core-tit-engine-v1-tits0-svil.cloudfinanza-svil.intesasanpaolo.com}/controlli/instances/find
        path: classpath:mocks/controlli/
        files:
          - listInstanceBySearchParamsOK.json
      ListInstanceInputConnector:
        url: ${CORE_ENGINE_URL:http://core-tit-engine-v1-tits0-svil.cloudfinanza-svil.intesasanpaolo.com}/controlli/{controlloId}/instances/{instanceId}/input
        path: classpath:mocks/controlli/
        files:
          - listInstanceInputOK.json
      ListInstanceOutputConnector:
        url: ${CORE_ENGINE_URL:http://core-tit-engine-v1-tits0-svil.cloudfinanza-svil.intesasanpaolo.com}/controlli/{controlloId}/instances/{instanceId}/output
        path: classpath:mocks/controlli/
        files:
          - listInstanceOutputOK.json
      ListLatestInstanceConnector:
        url: ${CORE_ENGINE_URL:http://core-tit-engine-v1-tits0-svil.cloudfinanza-svil.intesasanpaolo.com}/controlli/instances/latest
        path: classpath:mocks/controlli/
        files:
          - listLatestInstanceOK.json
      StartNewInstanceConnector:
        url: ${CORE_ENGINE_URL:http://core-tit-engine-v1-tits0-svil.cloudfinanza-svil.intesasanpaolo.com}/controlli/{controlloId}/start-request
        path: classpath:mocks/controlli/
        files:
          - startNewInstanceOK.json
      StartOldInstanceConnector:
        url: ${CORE_ENGINE_URL:http://core-tit-engine-v1-tits0-svil.cloudfinanza-svil.intesasanpaolo.com}/controlli/{controlloId}/instances/{instanceId}/start-request
        path: classpath:mocks/controlli/
        files:
          - startOldInstanceOK.json
      StopRunningInstanceConnector:
        url: ${CORE_ENGINE_URL:http://core-tit-engine-v1-tits0-svil.cloudfinanza-svil.intesasanpaolo.com}/controlli/{controlloId}/instances/{instanceId}/stop-request
        path: classpath:mocks/controlli/
        files:
          - stopRunningInstanceOK.json
      UpdateAllInputConnector:
        url: ${CORE_ENGINE_URL:http://core-tit-engine-v1-tits0-svil.cloudfinanza-svil.intesasanpaolo.com}/controlli/{controlloId}/input
        path: classpath:mocks/controlli/
        files:
          - updateAllInputOK.json
      UpdateControlloConnector:
        url: ${CORE_ENGINE_URL:http://core-tit-engine-v1-tits0-svil.cloudfinanza-svil.intesasanpaolo.com}/controlli/{controlloId}
        path: classpath:mocks/controlli/
        files:
          - updateControlloOK.json
      UpdateControlloInstanceConnector:
        url: ${CORE_ENGINE_URL:http://core-tit-engine-v1-tits0-svil.cloudfinanza-svil.intesasanpaolo.com}/controlli/{controlloId}/instances/{instanceId}
        path: classpath:mocks/controlli/
        files:
          - updateControlloInstanceOK.json
      ListInputByDateConnector:
        url: ${CORE_ENGINE_URL:http://core-tit-engine-v1-tits0-svil.cloudfinanza-svil.intesasanpaolo.com}/controlli/{controlloId}/input/date/{dataEsecuzione}
        path: classpath:mocks/controlli/
        files:
          - listInputByDateOK.json
      ListLatestInstanceByDateConnector:
        url: ${CORE_ENGINE_URL:http://core-tit-engine-v1-tits0-svil.cloudfinanza-svil.intesasanpaolo.com}/controlli/instances/latest/date/{dataEsecuzione}
        path: classpath:mocks/controlli/
        files:
          - listLatestInstanceOK.json
      GetControlloByIdAndSchedulazioneConnector:
        url: ${CORE_ENGINE_URL:http://core-tit-engine-v1-tits0-svil.cloudfinanza-svil.intesasanpaolo.com}/controlli/{controlloId}/schedulazione/{schedulazione}/date/{dataInizio}
        path: classpath:mocks/controlli/
        files:
          - getControlloByIdAndSchedulazioneOK.json
      UpdateByIdAndSchedulazioneControlloConnector:
        url: ${CORE_ENGINE_URL:http://core-tit-engine-v1-tits0-svil.cloudfinanza-svil.intesasanpaolo.com}/controlli/{controlloId}/schedulazione/{schedulazione}/date/{dataInizio}
        path: classpath:mocks/controlli/
        files:
          - updateByIdAndSchedulazioneControlloOK.json


      DeleteAcquisizioneConfigurazioneConnector:
        url: ${CORE_ENGINE_URL:http://core-tit-engine-v1-tits0-svil.cloudfinanza-svil.intesasanpaolo.com}/acquisizioni/configurazioni/{configId}
        path: classpath:mocks/acquisizioni/
        files:
          - deleteAcquisizioneConfigurazioneOK.json
      GetAcquisizioneConfigurazioneConnector:
        url: ${CORE_ENGINE_URL:http://core-tit-engine-v1-tits0-svil.cloudfinanza-svil.intesasanpaolo.com}/acquisizioni/configurazioni/{configId}
        path: classpath:mocks/acquisizioni/
        files:
          - getAcquisizioneConfigurazioneOK.json
      ListAcquisizionePayloadConnector:
        url: /acquisizioni/{acquisizioneId}/date/{dataEsecuzione}
        path: classpath:mocks/acquisizioni/
        files:
          - listAcquisizionePayloadOK.json
      InsertAcquisizioneConfigurazioneConnector:
        url: ${CORE_ENGINE_URL:http://core-tit-engine-v1-tits0-svil.cloudfinanza-svil.intesasanpaolo.com}/acquisizioni/configurazioni
        path: classpath:mocks/acquisizioni/
        files:
          - insertAcquisizioneConfigurazioneOK.json
      ListAcquisizioneBySearchParamsConnector:
        url: ${CORE_ENGINE_URL:http://core-tit-engine-v1-tits0-svil.cloudfinanza-svil.intesasanpaolo.com}/acquisizioni/find
        path: classpath:mocks/acquisizioni/
        files:
          - listAcquisizioneBySearchParamsOK.json
      ListAcquisizioneConfigurazioneConnector:
        url: ${CORE_ENGINE_URL:http://core-tit-engine-v1-tits0-svil.cloudfinanza-svil.intesasanpaolo.com}/acquisizioni/configurazioni
        path: classpath:mocks/acquisizioni/
        files:
          - listAcquisizioneConfigurazioneOK.json
      UpdateAcquisizioneConfigurazioneConnector:
        url: ${CORE_ENGINE_URL:http://core-tit-engine-v1-tits0-svil.cloudfinanza-svil.intesasanpaolo.com}/acquisizioni/configurazioni/{configId}
        path: classpath:mocks/acquisizioni/
        files:
          - updateAcquisizioneConfigurazioneOK.json


      DeleteCurvaConnector:
        url: ${CORE_ENGINE_URL:http://core-tit-engine-v1-tits0-svil.cloudfinanza-svil.intesasanpaolo.com}/curve/{nomeCurva}/date/{dataEsecuzione}/time/{oraEsecuzione}
        path: classpath:mocks/curve/
        files:
          - deleteCurvaOK.json
      GetCurvaConnector:
        url: ${CORE_ENGINE_URL:http://core-tit-engine-v1-tits0-svil.cloudfinanza-svil.intesasanpaolo.com}/curve/{nomeCurva}/date/{dataEsecuzione}/time/{oraEsecuzione}
        path: classpath:mocks/curve/
        files:
          - getCurvaOK.json
      InsertCurvaConnector:
        url: ${CORE_ENGINE_URL:http://core-tit-engine-v1-tits0-svil.cloudfinanza-svil.intesasanpaolo.com}/curve
        path: classpath:mocks/curve/
        files:
          - insertCurvaOK.json
      ListCurvaBySearchParamsConnector:
        url: ${CORE_ENGINE_URL:http://core-tit-engine-v1-tits0-svil.cloudfinanza-svil.intesasanpaolo.com}/curve/find
        path: classpath:mocks/curve/
        files:
          - listCurvaBySearchParamsOK.json
      UpdateCurvaConnector:
        url: ${CORE_ENGINE_URL:http://core-tit-engine-v1-tits0-svil.cloudfinanza-svil.intesasanpaolo.com}/curve/{nomeCurva}/date/{dataEsecuzione}/time/{oraEsecuzione}
        path: classpath:mocks/curve/
        files:
          - updateCurvaOK.json
      ListCurvaSearchIntervalConnector:
        url: ${CORE_ENGINE_URL:http://core-tit-engine-v1-tits0-svil.cloudfinanza-svil.intesasanpaolo.com}/curve/date/interval/find
        path: classpath:mocks/curve/
        files:
          - listCurvaSearchIntervalOK.json
      ListAllCurvaConnector:
        url: ${CORE_ENGINE_URL:http://core-tit-engine-v1-tits0-svil.cloudfinanza-svil.intesasanpaolo.com}/curve/all
        path: classpath:mocks/curve/
        files:
          - listAllCurvaOK.json
      ListAllAssetConnector:
        url: ${CORE_ENGINE_URL:http://core-tit-engine-v1-tits0-svil.cloudfinanza-svil.intesasanpaolo.com}/curve/asset/find
        path: classpath:mocks/curve/
        files:
          - listAllAssetOK.json


      DeleteNotaConnector:
        url: ${CORE_ENGINE_URL:http://core-tit-engine-v1-tits0-svil.cloudfinanza-svil.intesasanpaolo.com}/note/{idNota}
        path: classpath:mocks/note/
        files:
          - deleteNotaOK.json
      InsertNotaConnector:
        url: ${CORE_ENGINE_URL:http://core-tit-engine-v1-tits0-svil.cloudfinanza-svil.intesasanpaolo.com}/note
        path: classpath:mocks/note/
        files:
          - insertNotaOK.json
      ListNotaConnector:
        url: ${CORE_ENGINE_URL:http://core-tit-engine-v1-tits0-svil.cloudfinanza-svil.intesasanpaolo.com}/note/modulo/{modulo}
        path: classpath:mocks/note/
        files:
          - listNotaOK.json


      DeleteInputAnagraficaControlloConnector:
        url: ${CORE_ENGINE_URL:http://core-tit-engine-v1-tits0-svil.cloudfinanza-svil.intesasanpaolo.com}/anagrafica/input/{controlloId}
        path: classpath:mocks/anagrafica/
        files:
          - deleteInputAnagraficaControlloOK.json
      GetAnagraficaControlloConnector:
        url: ${CORE_ENGINE_URL:http://core-tit-engine-v1-tits0-svil.cloudfinanza-svil.intesasanpaolo.com}/anagrafica
        path: classpath:mocks/anagrafica/
        files:
          - getAnagraficaControlloOK.json
      InsertInputAnagraficaControlloConnector:
        url: ${CORE_ENGINE_URL:http://core-tit-engine-v1-tits0-svil.cloudfinanza-svil.intesasanpaolo.com}/anagrafica/input/{controlloId}
        path: classpath:mocks/anagrafica/
        files:
          - insertInputAnagraficaControlloOK.json
      ListAnagraficaBySearchParamsConnector:
        url: ${CORE_ENGINE_URL:http://core-tit-engine-v1-tits0-svil.cloudfinanza-svil.intesasanpaolo.com}/anagrafica/find
        path: classpath:mocks/anagrafica/
        files:
          - listAnagraficaBySearchParamsOK.json
      ListAnagraficaControlloConnector:
        url: ${CORE_ENGINE_URL:http://core-tit-engine-v1-tits0-svil.cloudfinanza-svil.intesasanpaolo.com}/anagrafica
        path: classpath:mocks/anagrafica/
        files:
          - listAnagraficaControlloOK.json
      UpdateAnagraficaControlloConnector:
        url: ${CORE_ENGINE_URL:http://core-tit-engine-v1-tits0-svil.cloudfinanza-svil.intesasanpaolo.com}/anagrafica/{controlloId}
        path: classpath:mocks/anagrafica/
        files:
          - updateAnagraficaControlloOK.json
      UpdateInputAnagraficaControlloConnector:
        url: ${CORE_ENGINE_URL:http://core-tit-engine-v1-tits0-svil.cloudfinanza-svil.intesasanpaolo.com}/anagrafica/input/{controlloId}
        path: classpath:mocks/anagrafica/
        files:
          - updateInputAnagraficaControlloOK.json
      ListAnagraficaInputOutputControlloConnector:
        url: ${CORE_ENGINE_URL:http://core-tit-engine-v1-tits0-svil.cloudfinanza-svil.intesasanpaolo.com}/anagrafica/input/{controlloId}
        path: classpath:mocks/anagrafica/
        files:
          - listAnagraficaInputOutputControlloOK.json
  jpaConfigurations:
    connection:
      url: ${DATASOURCE_TIT_URL:jdbc:oracle:thin:@//infe0m1t-scan-svl.syssede.systest.sanpaoloimi.com:1521/STITS0ONS}
      driver-class-name: oracle.jdbc.OracleDriver
      username: ${DATASOURCE_TIT_USERNAME:TITS0_APPPRD}
      password: ${DATASOURCE_TIT_PASSWORD:TITS0_APPPRD}
      connectionPoolSize: 5
      batch-size: 30
      timeout: 6000
      hibernateDialect: org.hibernate.dialect.Oracle10gDialect
      hbm2ddl: none
      mocked: false
      repositories:
        - DtConfigFileRepository
        - DtConfigParserRepository
        - DtCtrlAnagRepository
        - DtCtrlInputAnagRepository
        - DtCtrlScheduleAnagRepository
        - DtCurveAnagRepository
        - DtRulesRepository
        - DtUtilityLogRepository
        - StBbgLastprixRepository
        - WtCurveManRepository
        - WtCurveRepository
        - WtInputCtrlRepository
        - WtJavaLogRepository
        - WtMonitorLogRepository
        - WtOuputCtrlRepository
        - WtRunCtrlRepository
  jdbcConfigurations:
    default:
      uri: ${DATASOURCE_TIT_URL:jdbc:oracle:thin:@//infe0m1t-scan-svl.syssede.systest.sanpaoloimi.com:1521/STITS0ONS}
      driver-class-name: oracle.jdbc.OracleDriver
      username: ${DATASOURCE_TIT_USERNAME:TITS0_APPPRD}
      password: ${DATASOURCE_TIT_PASSWORD:TITS0_APPPRD}
      connectionPoolSize: 5
      timeout: 6000
      mocked: false
      enabledTracing: false
      path:
      files:
    items:
      DvEngineCurveConnector:
        uri: ${connectors.jdbcConfigurations.default.uri}
      DtCtrlInputAnagConnector:
        uri: ${connectors.jdbcConfigurations.default.uri}
      DtCurveAnagConnector:
        uri: ${connectors.jdbcConfigurations.default.uri}
      WtCurveConnector:
        uri: ${connectors.jdbcConfigurations.default.uri}
      WtInputCtrlConnector:
        uri: ${connectors.jdbcConfigurations.default.uri}
      DvInstanceInputConnector:
        uri: ${connectors.jdbcConfigurations.default.uri}
      DtCtrlParamConnector:
        uri: ${connectors.jdbcConfigurations.default.uri}
      WtOutputCtrlConnector:
        uri: ${connectors.jdbcConfigurations.default.uri}
      DtCtrlInputAnagCurveConnector:
        uri: ${connectors.jdbcConfigurations.default.uri}
      DtBatchConfigurationConnector:
        uri: ${connectors.jdbcConfigurations.default.uri}
      DvCurveAnagAcquisizioniConnector:
        uri: ${connectors.jdbcConfigurations.default.uri}
      DvMonitorLogCurveConnector:
        uri: ${connectors.jdbcConfigurations.default.uri}
      DtNoteConnector:
        uri: ${connectors.jdbcConfigurations.default.uri}
      DtCtrlScheduleAnagConnector:
        uri: ${connectors.jdbcConfigurations.default.uri}
      DtCtrlAnagConnector:
        uri: ${connectors.jdbcConfigurations.default.uri}
      SeqIdRunConnector:
        uri: ${connectors.jdbcConfigurations.default.uri}
      DtCtrlInputOutputAnagConnector:
        uri: ${connectors.jdbcConfigurations.default.uri}
      WtCtrlInputAnagConnector:
        uri: ${connectors.jdbcConfigurations.default.uri}
      WtRunCtrlConnector:
        uri: ${connectors.jdbcConfigurations.default.uri}
      WtRunDealConnector:
        uri: ${connectors.jdbcConfigurations.default.uri}  
      WtRunNoteConnector:
        uri: ${connectors.jdbcConfigurations.default.uri}
      DtDealFilterConnector:
        uri: ${connectors.jdbcConfigurations.default.uri}  
      WtRunDealMaConnector:
        uri: ${connectors.jdbcConfigurations.default.uri}  
      DvDetailDealConnector:
        uri: ${connectors.jdbcConfigurations.default.uri}  
        
#### Security configuration
keycloak:
  enabled: ${KEYCLOAK_ENABLED:false}
  auth-server-url: ${API_GATEWAY_URL:https://gwad0-svil.syssede.systest.sanpaoloimi.com/auth/oauth}
  resource: ${RESOURCE_NAME:""}
  realm: ${REALM_ID:ocp}
  public-client: true
  ssl-required: external
  confidential-port: 0
  use-resource-role-mappings: true
  principal-attribute: preferred_username
  bearer-only: true
  autodetect-bearer-only: true
  token-store: cookie
  security-constraints:
    - auth-roles:
        - openid
      security-collections:
        - name: reserved
          patterns:
            - /external/*

