spring:
  profiles:
    active: local
---
server:
  port:
    8079
spring:
  config:
    activate:
      on-profile: local
  kafka:
    template:
      default-topic: library-events
    producer:
      #bootstrap-servers: 192.168.1.164:9092,192.168.1.164:9093,192.168.1.164:9094
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        acks: all
        retries: 10
        retry.backoff.ms: 1000
    admin:
      properties:
        #bootstrap.servers: 192.168.1.164:9092,192.168.1.164:9093,192.168.1.164:9094
        bootstrap.servers: localhost:9092